### PR TITLE
Change drag content background color opacity by rgba

### LINKED ISSUE #127: Drag part of other person's opacity is too high
**What happened**: Drag part of other person's opacity is too high. So It's hard to recognize letters.
codepair

**What you expected to happen**: Darg part of other person should be near 0.1.
google_docs

**How to reproduce it (as minimally and precisely as possible)**: When drags text, text on another browser is dragged.  

**Environment**:
- Operating system: Ubuntu 20.04
- Browser and version: Chrome 92 and Firefox 90

### PR DESCRIPTION
**Pull request by SimYunSup**
Change drag content background color opacity by rgba, not by opacity.

#### What this PR does / why we need it?

image

Change drag content background color opacity by rgba, not by opacity. So It made the letters recognizable.

#### Any background context you want to provide?

metaData's color is expressed by hex. So I changed it rgba and lower the opacity.

#### What are the relevant tickets?

Fixes #127

### Checklist
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

File: webapp/src/components/Editor/CodeEditor/Cursor.ts [hunk 1]
```diff
@@ -66,9 +66,15 @@ export default class Cursor {
   updateLine(cm: CodeMirror.Editor, fromPos: CodeMirror.Position, toPos: CodeMirror.Position) {
     this.removeLine();
     this.status = CursorStatus.Activated;
+    // Change HEX to RGBA
+    const redColor = parseInt(this.color.slice(1, 3), 16);
+    const greenColor = parseInt(this.color.slice(3, 5), 16);
+    const blueColor = parseInt(this.color.slice(5, 7), 16);
+    // opacity apply by rgba, not opacity.
+    const backgroundColor = `rgba(${redColor}, ${greenColor}, ${blueColor}, 0.15)`;
```
Comment (hackerwins) [inline webapp/src/components/Editor/CodeEditor/Cursor.ts:74]: The code is clear, so it would be nice to combine the comments into one.

```suggestion
    // Apply transparency to the background of selection.
    const redColor = parseInt(this.color.slice(1, 3), 16);
    const greenColor = parseInt(this.color.slice(3, 5), 16);
    const blueColor = parseInt(this.color.slice(5, 7), 16);
    const backgroundColor = `rgba(${redColor}, ${greenColor}, ${blueColor}, 0.15)`;
```

**Review by hackerwins — APPROVED** [review]
LGTM. 👍

**Review by ppeeou — APPROVED** [review]
Thank you for your task 👍
