### PR TITLE
When an error existed, display first

### LINKED ISSUE #46: When communication error with Agent occurs, error tooltip does not appear
**What happened**:

When a communication error with Agent occurs, the error tooltip does not appear.

Screen Shot 2021-02-21 at 11 46 28

**What you expected to happen**:

A tooltip should appear for the error.

**How to reproduce it (as minimally and precisely as possible)**:

Connect to codepair with agent turned off.

**Anything else we need to know?**:

It is assumed that it does not work after refactoring. #43

**Environment**:
- Operating system: macOS Big Sur, Version 11.2.1
- Browser and version: Version 88.0.4324.182 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by ppeeou**
#### What are the relevant tickets?

Fixes #46 

### Checklist
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

File: src/components/Editor/index.tsx [hunk 1]
```diff
@@ -92,18 +92,6 @@ export default function Editor(props: { docKey: string }) {
     };
   }, [docKey, client, doc]);
 
-  if (!client || !doc) {
-    return null;
-  }
```
Comment (ppeeou) [inline src/components/Editor/index.tsx:97]: The reason for removing this line is that the client and doc object always exist when loading is false.
